# YAML Yet another markup language
info:
  version: "1.0.5"
  website: "sarthakjain.com"

database:
  type: 'sqlite'
  path: /var/bin/*.json

routes:
  - path: /api/
    methods: ['GET','POST']
  - path: /admin
    method: [PUT]
OperatingSystem:
  - Windows:
    - windows 11
    - windows 12
  - Mashintosh
  - Linux:
    - ubuntu: True
      Solaris: No
  - IOS
  - Android

description1: | 
  it is yaml
  tutorial
  of break line print
description2: >
  it will eliminate single line 
  from

  each row

player: &player_anchor
  name: myname
  min_age: 25
  qualification: Undergrad

hockey:
  <<: *player_anchor
  name: Sarthak Jain